import {spawnSync} from 'node:child_process';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,statSync,unlinkSync,readdirSync} from 'node:fs';
import {join,resolve} from 'node:path';import {tmpdir} from 'node:os';import {createHash} from 'node:crypto';
const candidate=resolve(process.argv[2]||'.'),out=resolve(process.argv[3]||join(candidate,'reports/native-evidence-p02-2026-09-30/technical')),root=mkdtempSync(join(tmpdir(),'codeweb-p02-supplement-'));
mkdirSync(join(out,'receipts'),{recursive:true});
const hash=s=>createHash('sha256').update(s).digest('hex');const receipts=[];
function run(id,script,args=[],input,extra={}){const argv=[join(candidate,script),...args],start=new Date().toISOString(),t=performance.now();const env={...process.env,CODEWEB_NO_STATS:'1',CODEWEB_NO_AUTOREFRESH:'1',...extra};const r=spawnSync(process.execPath,argv,{cwd:root,env,input,encoding:'utf8',timeout:90000,maxBuffer:32<<20});const record={id,command:[process.execPath,...argv],cwd:root,envOverrides:{CODEWEB_NO_STATS:'1',CODEWEB_NO_AUTOREFRESH:'1',...extra},stdin:input??null,start,end:new Date().toISOString(),durationMs:performance.now()-t,exit:r.status,signal:r.signal,error:r.error?.message??null,stdout:r.stdout??'',stderr:r.stderr??''};writeFileSync(join(out,'receipts',id+'.json'),JSON.stringify(record,null,2));receipts.push(record);return record;}
function ownrun(id,args,extra={}){const start=new Date().toISOString(),t=performance.now();const r=spawnSync(process.execPath,args,{cwd:candidate,env:{...process.env,...extra},encoding:'utf8',timeout:90000,maxBuffer:32<<20});const record={id,command:[process.execPath,...args],cwd:candidate,envOverrides:extra,start,end:new Date().toISOString(),durationMs:performance.now()-t,exit:r.status,signal:r.signal,error:r.error?.message??null,stdout:r.stdout??'',stderr:r.stderr??''};writeFileSync(join(out,'receipts',id+'.json'),JSON.stringify(record,null,2));receipts.push(record);return record;}
function mcp(id,name,args){return run(id,'scripts/mcp-server.mjs',[],JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name,arguments:args}})+'\n');}
function write(p,s){mkdirSync(join(p,'..'),{recursive:true});writeFileSync(p,s);}
function seed(dir){mkdirSync(dir);mkdirSync(join(dir,'.codeweb'));write(join(dir,'subject.mjs'),'export function low(value) {\n return value + 1;\n}\nexport function popular(value) {\n return value * 2;\n}\n');write(join(dir,'consequential.mjs'),"import {low} from './subject.mjs';\nexport function consequential() {\n return low(10);\n}\n");for(let i=0;i<5;i++)write(join(dir,`p${i}.mjs`),`import {popular} from './subject.mjs';\nexport function p${i}() {\n return popular(${i});\n}\n`);const gp=join(dir,'.codeweb','graph.json');write(gp,JSON.stringify({meta:{root:dir},nodes:[],edges:[],overlaps:[],domains:[]}));return gp;}
const dir=join(root,'fresh'),gp=seed(dir);run('T63-fresh-refresh','scripts/refresh.mjs',[gp,'--json']);
run('T64-fresh-context','scripts/context-pack.mjs',[gp,'low','--json']);const payload=JSON.stringify({tool_name:'Edit',tool_input:{file_path:join(dir,'subject.mjs'),old_string:'value + 1',new_string:'value + 2'}});run('T65-fresh-hook','hooks/pre-edit-impact.mjs',[],payload);
write(join(dir,'subject.mjs'),readFileSync(join(dir,'subject.mjs'),'utf8')+'// behind\n');run('T66-stale-stamped-hook','hooks/pre-edit-impact.mjs',[],payload);
run('T67-codex-shaped-hook','hooks/pre-edit-impact.mjs',[],JSON.stringify({tool_name:'apply_patch',tool_input:{command:'*** Begin Patch\n*** Update File: '+join(dir,'subject.mjs')+'\n@@\n- return value + 1;\n+ return value + 2;\n*** End Patch'}}));
const faildir=join(root,'extraction-fail');mkdirSync(faildir);mkdirSync(join(faildir,'.codeweb'));const fgp=join(faildir,'.codeweb','graph.json');write(fgp,JSON.stringify({meta:{root:faildir},nodes:[{id:'subject.mjs:low',label:'low',kind:'function',file:'subject.mjs',line:1,loc:3}],edges:[{from:'consumer.mjs:consumer',to:'subject.mjs:low',kind:'call'}]}));run('T68-real-extraction-failure-hook','hooks/post-edit-diff.mjs',[],JSON.stringify({tool_name:'Edit',tool_input:{file_path:join(faildir,'subject.mjs')}}));run('T69-real-extraction-failure-cli','scripts/refresh.mjs',[fgp,'--json']);
const sim=join(root,'intentional');mkdirSync(sim);mkdirSync(join(sim,'.codeweb'));const source=`export function packOrders(list) {\n const out = [];\n let total = 0;\n for (const it of list) {\n total += it.qty;\n out.push(it.qty * 2);\n }\n const avg = total / list.length;\n out.sort();\n console.log(avg);\n return out;\n}\n`;write(join(sim,'one.mjs'),source);write(join(sim,'two.mjs'),source);const sg=JSON.parse(run('T70-intentional-extract','scripts/extract-symbols.mjs',[sim,'--no-ctags','--engine','regex']).stdout);const sp=join(sim,'.codeweb','graph.json');write(sp,JSON.stringify({...sg,overlaps:[],domains:[]}));
run('T71-corrected-overlap','scripts/overlap.mjs',[],undefined,{CODEWEB_WS:join(sim,'.codeweb')});const overlapGraph=JSON.parse(readFileSync(sp));const finding=overlapGraph.overlaps?.find(f=>f.kind==='duplicate-logic');write(join(out,'intentional-finding-before.json'),JSON.stringify(overlapGraph.overlaps,null,2));
if(finding){const fp=(await import(join(candidate,'scripts/lib/annotations.mjs'))).fingerprint(finding);run('T72-intentional-dismissal','scripts/annotate.mjs',['--dir',join(sim,'.codeweb'),'--suppress',fp,'--note','Intentional separate boundary fixtures; preserve duplicate implementations.','--json']);run('T73-dismissal-repeat-overlap','scripts/overlap.mjs',[],undefined,{CODEWEB_WS:join(sim,'.codeweb')});write(join(out,'intentional-finding-after.json'),readFileSync(sp));}
mcp('T74-corrected-mcp-similarity','codeweb_find_similar',{graph:sp,body:source});
const empty=join(root,'empty.json');write(empty,JSON.stringify({meta:{root},nodes:[],edges:[],overlaps:[]}));run('T75-empty-deadcode-json','scripts/deadcode.mjs',[empty,'--json']);
const incomplete=join(root,'incomplete.json');write(incomplete,JSON.stringify({meta:{root,analysis:{status:'incomplete',diagnosticCount:1,diagnostics:[{code:'unsupported-declaration',file:'missing.mjs',line:1}]}},nodes:[{id:'missing.mjs:risky',label:'risky',kind:'function',file:'missing.mjs',line:1,loc:3,exports:false}],edges:[],overlaps:[]}));run('T76-incomplete-deadcode-json','scripts/deadcode.mjs',[incomplete,'--json']);mcp('T77-incomplete-deadcode-mcp','codeweb_deadcode',{graph:incomplete});
// Correct our isolated suite environment only: retention's stats assertion requires the default statistics setting.
ownrun('T78-corrected-stats-test',['--test','--test-name-pattern','stats: full maps stamp',join(candidate,'tests/retention.test.mjs')],{CODEWEB_NO_STATS:'0'});
// Actual author-owned runner coverage, kept separately from the synthetic import in the first probe.
const behave=join(root,'behavior');mkdirSync(behave);mkdirSync(join(behave,'.codeweb'));write(join(behave,'subject.mjs'),'export function low(value) {\n return value + 1;\n}\n');write(join(behave,'current.test.mjs'),"import test from 'node:test';\nimport assert from 'node:assert/strict';\nimport {low} from './subject.mjs';\ntest('measured own-fixture oracle',()=>assert.equal(low(2),3));\n");
const br=ownrun('T79-current-executed-coverage',['--test','--experimental-test-coverage','--test-reporter=lcov',join(behave,'current.test.mjs')]);write(join(behave,'measured.lcov'),br.stdout);const bgraph=JSON.parse(run('T80-measured-extract','scripts/extract-symbols.mjs',[behave,'--no-ctags','--engine','regex']).stdout),bgp=join(behave,'.codeweb','graph.json');write(bgp,JSON.stringify({...bgraph,overlaps:[]}));run('T81-import-executed-coverage','scripts/coverage.mjs',[bgp,join(behave,'measured.lcov'),'--json']);run('T82-executed-coverage-explain','scripts/explain.mjs',[bgp,'low','--json']);const before=hash(readFileSync(join(behave,'subject.mjs')));write(join(behave,'subject.mjs'),'export function low(value) {\n return value + 2;\n}\n');run('T83-executed-stale-coverage-explain','scripts/explain.mjs',[bgp,'low','--json']);ownrun('T84-current-after-edit-fails',['--test',join(behave,'current.test.mjs')]);write(join(out,'executed-coverage-provenance.json'),JSON.stringify({runnerReceipt:'receipts/T79-current-executed-coverage.json',sourceBeforeSha256:before,sourceAfterSha256:hash(readFileSync(join(behave,'subject.mjs'))),coverageSha256:hash(br.stdout),root:behave},null,2));
write(join(out,'SUPPLEMENT.json'),JSON.stringify({root,corrections:[{original:'T49-mcp-similarity',corrected:'T74-corrected-mcp-similarity',reason:'Our probe passed unsupported k to MCP; retry omits k.'},{original:'T50-overlap',corrected:'T71-corrected-overlap',reason:'Our probe passed graph as a positional arg; overlap uses scoped CODEWEB_WS.'},{original:'T62-targeted-suites',corrected:'T78-corrected-stats-test',reason:'Our CODEWEB_NO_STATS=1 hid required stats. Rerun only the failing test with default enabled.'}],receipts:receipts.map(r=>({id:r.id,exit:r.exit,durationMs:r.durationMs}))},null,2));console.log(JSON.stringify({root,runs:receipts.length,tests:receipts.find(r=>r.id==='T78-corrected-stats-test').exit}));
